[code]
editor = "code"
lang = "<LANGUAGE>"
pick = "${fid}_${slug}"
edit_code_marker = true
start_marker = "<COMMENT> start_submission"
end_marker = "<COMMENT> end_submission"
inject_before = "<INJECT_BEFORE>"

[cookies]
csrf = "<CSRFTOKEN>"
session = "<LEETCODE_SESSION>"
site = "leetcode.com"

[storage]
cache = "problems"
code = "<CODE_LOCATION>"
root = "~/.leetcode"
scripts = "scripts"
